# repo-a/mkdocs.yml
INHERIT: docs/_core/core.mkdocs.yml

# region Site
site_url: https://docs.singulargenomics.com/G4X-viewer/
site_description: Singular Genomics G4X-viewer documentation site

repo_name: G4X-viewer
repo_url: https://github.com/Singular-Genomics/G4X-viewer

theme:
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes


nav:
  - Docs Home: https://docs.singulargenomics.com
  - G4X-helpers: https://docs.singulargenomics.com/G4X-helpers/

  - G4X-viewer:
    - Home: index.md
    - Usage:
      - overview: usage/index.md
      - source files: usage/source_files.md
      - on-screen controls: usage/on_screen_controls.md
      - protein: usage/protein.md
      - fH&E: usage/fhe.md
      - transcript: usage/transcript.md
      - segmentation: usage/segmentation.md
      - UMAP filter: usage/umap.md
      - flow cytometry filter: usage/flow_cytometry.md
    - Dashboard:
      - overview: dashboard/index.md
      - ROI selection: dashboard/roi_selection.md
      - expression box chart: dashboard/expression_box_chart.md
      - pie chart: dashboard/pie_chart.md
      - expression bar chart: dashboard/expression_bar_chart.md
      - heatmap chart: dashboard/expression_heatmap.md
    - Resources: resources.md
    - Contribute: contributing.md

